name: helm-package
on:
  push:
    branches:
    - master
    paths:
    - 'deploy/charts/oldmonk/**'
env:
  HELM_CHART_URL: "https://remotegarage.github.io/oldmonk/helm-charts/"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Helm
      run: |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm init --client-only
    - name: Check Chart Version
      run: |
        helm repo add remotegarage ${{ env.HELM_CHART_URL }}
        helm search remotegarage/oldmonk --version `cat deploy/charts/oldmonk/Chart.yaml | grep '^version: [[:alnum:]]' | awk '{print $2}'` > HELM_CHART_STATUS.txt
        HELM_CHART_STATUS=`cat HELM_CHART_STATUS.txt`
        if [ "${HELM_CHART_STATUS}" != 'No results found' ]; then
          echo 'Version already exist, impossible to continue...'
          exit 1
        fi
    - name: Check sintax
      run: helm lint deploy/charts/oldmonk/
    - name: Create package
      run: |
        mkdir -p output/
        helm package deploy/charts/oldmonk/ -d output/
    - name: Reindex repo
      run: |
        wget --quiet ${{ env.HELM_CHART_URL }}/index.yaml
        helm repo index --merge index.yaml --url ${{ env.HELM_CHART_URL }} output/
    - name: Release
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: output